name: create issue

on: workflow_dispatch

permissions: {}

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Get GitHub App User ID
        id: get-user-id
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "user-id=$(gh api "/users/${{ steps.app-token.output.app-slug }}[bot]" --jq .id)" >> $GITHUB_OUTPUT
      - name: Set up Git user stuff
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Comment on issue
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh issue comment 17 --body "hello right back"

